version: '2'
services:
    db:
        image: mysql:5.7
        container_name: nodeproject_db
        environment:
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "pass"
            MYSQL_DATABASE: "nodedb"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

        # Expose the internal 3306 port, but do not specify host port mapping. Docker will map it as it pleases and
        # prevent clashes to existing ports. This port exposure is for dev access only.
        ports:
            - "3306"
        networks:
            - main_network

    nodeproject_web_api:
        container_name: nodeproject_web_api
        image: nodeproject_web_api
        build: .
        networks: 
            - main_network

    redis:
        container_name: nodeproject_redis
        image: redis
        ports:
            - "6379"
        networks:
            - main_network

networks:
    main_network:
        driver: bridge
